/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArgentAccount } from "./ArgentAccount";
export type { l2_dai_wormhole_gateway } from "./l2_dai_wormhole_gateway";
